apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"n8n","environment":"production"},"name":"n8n","namespace":"n8n-prod"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"n8n"}},"template":{"metadata":{"labels":{"app":"n8n","environment":"production"}},"spec":{"containers":[{"env":[{"name":"N8N_HOST","value":"n8n.ii-us.com"},{"name":"N8N_PORT","value":"5678"},{"name":"N8N_PROTOCOL","value":"https"},{"name":"WEBHOOK_URL","value":"https://n8n.ii-us.com"},{"name":"GENERIC_TIMEZONE","value":"America/New_York"},{"name":"N8N_LOG_LEVEL","value":"info"},{"name":"N8N_USER_MANAGEMENT_DISABLED","value":"false"},{"name":"N8N_SECURE_COOKIE","value":"true"},{"name":"N8N_ENCRYPTION_KEY","valueFrom":{"secretKeyRef":{"key":"N8N_ENCRYPTION_KEY","name":"n8n-secrets"}}}],"image":"n8nio/n8n:1.105.4","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":5678},"initialDelaySeconds":30,"periodSeconds":10,"timeoutSeconds":5},"name":"n8n","ports":[{"containerPort":5678,"name":"http"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":5678},"initialDelaySeconds":10,"periodSeconds":5,"timeoutSeconds":3},"resources":{"limits":{"cpu":"200m","memory":"1Gi"},"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/home/node/.n8n","name":"n8n-data"}]}],"nodeSelector":{"kubernetes.io/os":"linux"},"securityContext":{"fsGroup":1000,"runAsNonRoot":true,"runAsUser":1000},"serviceAccountName":"n8n","volumes":[{"name":"n8n-data","persistentVolumeClaim":{"claimName":"n8n-data"}}]}}}}
  creationTimestamp: "2025-08-07T15:29:42Z"
  generation: 5
  labels:
    app: n8n
    environment: production
  name: n8n
  namespace: n8n-prod
  resourceVersion: "52678020"
  uid: c58e4821-90af-4720-a04f-e6d135cffe60
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: n8n
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: n8n
        environment: production
    spec:
      containers:
      - env:
        - name: N8N_HOST
          value: n8n.ii-us.com
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: https
        - name: WEBHOOK_URL
          value: https://n8n.ii-us.com
        - name: GENERIC_TIMEZONE
          value: America/New_York
        - name: N8N_LOG_LEVEL
          value: info
        - name: N8N_USER_MANAGEMENT_DISABLED
          value: "false"
        - name: N8N_SECURE_COOKIE
          value: "true"
        - name: N8N_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: N8N_ENCRYPTION_KEY
              name: n8n-secrets
        image: n8nio/n8n:1.105.4
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 5678
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: n8n
        ports:
        - containerPort: 5678
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 5678
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/node/.n8n
          name: n8n-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: n8n
      serviceAccountName: n8n
      terminationGracePeriodSeconds: 30
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-08-07T15:29:43Z"
    lastUpdateTime: "2025-08-07T16:07:10Z"
    message: ReplicaSet "n8n-d5cb5c9c5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-10-13T13:24:39Z"
    lastUpdateTime: "2025-10-13T13:24:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
