apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: n8n-premium-ssd
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
  cachingmode: ReadOnly
reclaimPolicy: Retain
allowVolumeExpansion: true
