# External Secrets Operator Contract Definitions
# These define the expected structure of ESO resources for this feature

---
# ClusterSecretStore - Cluster-wide connection to Azure Key Vault
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://${KEYVAULT_NAME}.vault.azure.net"
      serviceAccountRef:
        name: external-secrets-sa
        namespace: external-secrets

---
# ExternalSecret for n8n application secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-secrets
  namespace: n8n-prod
spec:
  refreshInterval: 4h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: n8n-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: n8n-encryption-key

---
# ExternalSecret for ArgoCD admin password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-admin-secret
  namespace: argocd
spec:
  refreshInterval: 4h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: admin.password
      remoteRef:
        key: argocd-admin-password

---
# ServiceAccount for External Secrets Operator with Workload Identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: "${MANAGED_IDENTITY_CLIENT_ID}"
  labels:
    azure.workload.identity/use: "true"
