# argocd/argocd-rbac-cm.yaml
# =============================================================================
# ArgoCD RBAC Configuration
# =============================================================================
# This ConfigMap controls role-based access control for ArgoCD users.
# It defines roles, permissions, and group mappings.
#
# RBAC Policy Format:
#   p, <subject>, <resource>, <action>, <project>/<object>, allow/deny
#   g, <user>, <role>
#
# Resources: applications, clusters, repositories, projects, accounts, certificates, gpgkeys, logs, exec
# Actions: get, create, update, delete, sync, override, action, *, ~
# =============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: rbac
data:
  # Default policy for authenticated users without specific role assignment
  # Options: role:readonly, role:admin, or custom role
  policy.default: role:readonly

  # RBAC policy rules (CSV format)
  policy.csv: |
    # ==========================================================================
    # Role Definitions
    # ==========================================================================

    # Admin role - full access to everything
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, certificates, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, logs, *, */*, allow
    p, role:admin, exec, *, */*, allow

    # Readonly role - view only access
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, logs, get, */*, allow

    # Operator role - can sync and manage applications but not infrastructure
    p, role:operator, applications, get, */*, allow
    p, role:operator, applications, sync, */*, allow
    p, role:operator, applications, action/*, */*, allow
    p, role:operator, applications, update, */*, allow
    p, role:operator, logs, get, */*, allow
    p, role:operator, clusters, get, *, allow
    p, role:operator, repositories, get, *, allow
    p, role:operator, projects, get, *, allow

    # ==========================================================================
    # User/Group to Role Mappings
    # ==========================================================================

    # Built-in admin user gets admin role
    g, admin, role:admin

    # Example: Map additional users to roles
    # g, devops-team, role:operator
    # g, developers, role:readonly

  # Scopes for OIDC tokens (used if SSO is configured)
  scopes: "[groups, email]"

  # Match mode for OIDC groups
  # Options: glob (default), regex
  policy.matchMode: "glob"
