apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n-backup
  namespace: n8n-prod
  annotations:
    azure.workload.identity/client-id: "your-managed-identity-client-id"
    azure.workload.identity/tenant-id: "your-tenant-id"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: n8n-backup-role
  namespace: n8n-prod
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: n8n-backup-rolebinding
  namespace: n8n-prod
subjects:
- kind: ServiceAccount
  name: n8n-backup
  namespace: n8n-prod
roleRef:
  kind: Role
  name: n8n-backup-role
  apiGroup: rbac.authorization.k8s.io
