apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n
  namespace: n8n-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: n8n-role
  namespace: n8n-prod
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: n8n-rolebinding
  namespace: n8n-prod
subjects:
- kind: ServiceAccount
  name: n8n
  namespace: n8n-prod
roleRef:
  kind: Role
  name: n8n-role
  apiGroup: rbac.authorization.k8s.io
